"""Add loan_id to Transaction

Revision ID: 4aacdbb5874d
Revises: 5de208586db0
Create Date: 2025-07-03 23:37:41.593615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aacdbb5874d'
down_revision = '5de208586db0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_transaction_loan_id', 'loan', ['loan_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint('fk_transaction_loan_id', type_='foreignkey')
        batch_op.drop_column('loan_id')

    # ### end Alembic commands ###
