"""Fix Transaction model and add loan_id

Revision ID: 5de208586db0
Revises: 52945698e2e3
Create Date: 2025-07-03 23:03:39.370958

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5de208586db0'
down_revision = '52945698e2e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transaction_loan_id'), type_='foreignkey')
        batch_op.drop_column('loan_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('loan_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_transaction_loan_id'), 'loan', ['loan_id'], ['id'])

    # ### end Alembic commands ###
