"""add category to expense

Revision ID: 866db0e8c32d
Revises: fb7a88f6f004
Create Date: 2025-07-04 16:06:57.426794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '866db0e8c32d'
down_revision = 'fb7a88f6f004'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_fixed_expense')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_fixed_expense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('repeat', sa.BOOLEAN(), nullable=True),
    sa.Column('repeat_until', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
