"""Add category column to FixedExpense

Revision ID: fb7a88f6f004
Revises: 4aacdbb5874d
Create Date: 2025-07-04 15:58:54.091620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb7a88f6f004'
down_revision = '4aacdbb5874d'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('fixed_expense') as batch_op:
        batch_op.add_column(
            sa.Column('category', sa.String(length=100), nullable=False, server_default='General')
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fixed_expense', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_income', sa.BOOLEAN(), nullable=True))
        batch_op.alter_column('date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.drop_column('category')

    op.create_table('_alembic_tmp_fixed_expense',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('category', sa.VARCHAR(length=100), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('amount', sa.FLOAT(), nullable=False),
    sa.Column('date', sa.DATE(), nullable=False),
    sa.Column('repeat', sa.BOOLEAN(), nullable=True),
    sa.Column('repeat_until', sa.DATE(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
